### ISSUE TITLE
How to get the TAX_file

### ISSUE THREAD

**Issue by Taojianchang** [dyxstat/HiCBin#1]
Dear sir,
I am using HiCBin to process my data, but the software TAXAassign does not work for me. Could you suggest any other method to get the TAX_file? Thanks.

**Comment by dyxstat** [comment]
Hi Jianchang,

Thanks for trying our software. However, unluckily, Tax_file can only be obtained by the TAXAassign software at the current stage.

Could you report the existed problems with your TAXassign, like if you got into trouble on installation; or otherwise could you share your log file of the TAXassign? 

Best

**Comment by Taojianchang** [comment]
Hello Yuxuan,

Thanks for your reply! I used the test.fasta to test TAXAassign, and got the files test_B.out, test_BF.out and test_BFT.out. However, the output test_ASSIGNMENTS.csv was a blank file. The final error occurred was: Generate taxonomic assignment tables from blastn hits with consensus threshold of 90%. Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /home/jianchang/software/TAXAassign/scripts/blast_gen_assignments.pl line 108. I'm not sure if there's a problem with the step ' Annotate blastn hits with NCBI's taxonomy data' , because the file test_BFT.out doesn't include taxonomy information. In addition, MySQL was installed and run as a non root user. The log file and the output files can be found here.

[TAXAassign.log.txt](https://github.com/dyxstat/HiCBin/files/7151119/TAXAassign.log.txt)
[test_B.txt](https://github.com/dyxstat/HiCBin/files/7151120/test_B.txt)
[test_BF.txt](https://github.com/dyxstat/HiCBin/files/7151122/test_BF.txt)
[test_BFT.txt](https://github.com/dyxstat/HiCBin/files/7151123/test_BFT.txt)

**Comment by dyxstat** [comment]
Hi Jianchang,

This mistake resulted from the perl version since '@array' has been deprecated for the latest perl version.
 
Please refer to https://github.com/umerijaz/TAXAassign/issues/6 for more details.

Moreover, if you don't have administrative permission to run MySQL on the cluster, you could use sqlite3 to store the database locally in the installation folder (https://github.com/umerijaz/TAXAassign/blob/master/README.md).  

Best

**Comment by Taojianchang** [comment]
Thanks for your suggestions! TAXAassign works now.
