### ISSUE TITLE
TAXAassign can't be installed.

### ISSUE THREAD

**Issue by JiaLonghao1997** [dyxstat/HiCBin#4]
HiCBin assign taxonomy to contigs by TAXAassign. But we can hardly install TAXAassign, can we use alternative tools, such as Kraken2(https://ccb.jhu.edu/software/kraken2/) or mmseqs2(https://github.com/soedinglab/mmseqs2/wiki#taxonomy-assignment)? 
Could you please give me some suggestion? Thank you!

**Comment by dyxstat** [comment]
Hi Longhao,

Thanks for trying our software. Could you report the problems with the installation of TAXassign? I might try my best to help you install it.

If you really want to use other software to label contigs, there are two points deserving your attention:  1) Contigs should be assigned to species level with high confidence and accuracy; 2) Taxonomy file should be in CSV format, where contig name should be in the first column and the species name should be in the seventh column (you can fill in the middle five columns with any strings since they are not used).

Best,
Yancey
